version: "3"
networks:
  default:
    external:
      name: nginx_shared
services:
  random-game-api:
    image: ryuyanninja/random-game-front-end:latest
    restart: always
    container_name: random-game-front-end
    env_file: .env
    expose:
      - 80